//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        public int Masp { get; set; }
        public string Tensp { get; set; }
        public Nullable<decimal> Giatien { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string Mota { get; set; }
        public Nullable<bool> Sanphammoi { get; set; }
        public string Anhbia { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<int> MaDM { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual Danhmucsanpham Danhmucsanpham { get; set; }
        public virtual Nhacungcap Nhacungcap { get; set; }
    }
}
